name: Lint

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: uubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'zulu'

      - name: Cache Gradle Dependencies
          uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Lint
        run: ./gradlew ktlintCheck